spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/local?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&useSSL=false'
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: root3306
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.crayon2f.dao